### ISSUE TITLE
Downstream improvements - including Riak + Service broker

### ISSUE THREAD

**Issue by james-masson** [cloudfoundry/cf-riak-cs-release#11]
Hi,

we've forked this release, and have been working on improvements to support Riak (without CS).

While we've diverged a bit, we've added a few new features to the Riak bosh release you might be interested in, including:

* Riak + CF service broker v2
* Running Riak as vcap user
* Compile Riak with BOSH friendly configuration.
* More tenacious cluster join process
* Support for the admin GUI
* Tests to verify cluster connectivity and data persistance across node reboot + node loss
* More use of ERB templating for Riak config files.
* Complete BOSH deployable CI test-suite for the above.

We'd like eventually to get this all merged upstream - but our changes have been fairly extensive.

Feel free to pull whatever code you like - contact @trastle for more details, as CloudCredo will be rolling off this project shortly.

regards

James M

**Comment by robdimsdale** [comment]
The upstream repo hasn't had any activity in two years, and we're not likely to merge changes at this point. Closing this issue.
