### ISSUE TITLE
is there a performance test of riak cs? the read/write speed is very low in my test!

### ISSUE THREAD

**Issue by HelloLin** [cloudfoundry/cf-riak-cs-release#16]
i want to use the riak cs as a cc blobstore in cloud foundry. but when i deploy the riak cs and write some data to riak cs. i found that the read/write speed is very slow. compare to nfs server. i use the s3curl to put data to riak cs .i have the test as below:

a 475M file write to riak cs need 1m53.915s but 9m23.342s in nfs server
a 296M file write to riak cs need 0m50.229s

it take me a long time when i cf push app. i want to know why cloudfoundry use the riak cs for cc blobstore? even the speed is 3x lower than nfs server? is there a Performance Tuning of riak cs when you use it as a blobstore?

i hope you can help me , thank you .

**Comment by robdimsdale** [comment]
It's been nearly two years without response; closing this now.
