### ISSUE TITLE
Bosh compilation of git package fail with stemcell 3093

### ISSUE THREAD

**Issue by fbonelle** [cloudfoundry/cf-riak-cs-release#38]
Bosh compilation of git package fail with stemcell 3093.

The failure trace:

Error 450001: Action Failed get_task: Task 15350037-d4ee-45ea-7689-f5f4aeeb286f result: Compiling package git: Running packaging script: Command exited with 1; Truncated stdout:     MSGFMT po/build/locale/sv/LC_MESSAGES/git.mo
    MSGFMT po/build/locale/vi/LC_MESSAGES/git.mo
    MSGFMT po/build/locale/zh_CN/LC_MESSAGES/git.mo
    CC test-chmtime.o
    CC test-ctype.o
    CC test-date.o
    CC test-delta.o
    CC test-dump-cache-tree.o
    CC test-genrandom.o
    CC test-index-version.o
    CC test-line-buffer.o
    CC test-match-trees.o
    CC test-mergesort.o
    CC test-mktemp.o
    CC test-parse-options.o
    CC test-path-utils.o
    CC test-prio-queue.o
    CC test-read-cache.o
    CC test-regex.o
    CC test-revision-walking.o
    CC test-run-command.o
    CC test-scrap-cache-tree.o
    CC test-sha1.o
    CC test-sigchain.o
    CC test-string-list.o
    CC test-subprocess.o
    CC test-svn-fe.o
    CC test-wildmatch.o
    GEN bin-wrappers/git
    GEN bin-wrappers/git-upload-pack
    GEN bin-wrappers/git-receive-pack
    GEN bin-wrappers/git-upload-archive
    GEN bin-wrappers/git-shell
    GEN bin-wrappers/git-cvsserver
    GEN bin-wrappers/test-chmtime
    GEN bin-wrappers/test-ctype
    GEN bin-wrappers/test-date
    GEN bin-wrappers/test-delta
    GEN bin-wrappers/test-dump-cache-tree
    GEN bin-wrappers/test-genrandom
    GEN bin-wrappers/test-index-version
    GEN bin-wrappers/test-line-buffer
    GEN bin-wrappers/test-match-trees
    GEN bin-wrappers/test-mergesort
    GEN bin-wrappers/test-mktemp
    GEN bin-wrappers/test-parse-options
    GEN bin-wrappers/test-path-utils
    GEN bin-wrappers/test-prio-queue
    GEN bin-wrappers/test-read-cache
    GEN bin-wrappers/test-regex
    GEN bin-wrappers/test-revision-walking
    GEN bin-wrappers/test-run-command
    GEN bin-wrappers/test-scrap-cache-tree
    GEN bin-wrappers/test-sha1
    GEN bin-wrappers/test-sigchain
    GEN bin-wrappers/test-string-list
    GEN bin-wrappers/test-subprocess
    GEN bin-wrappers/test-svn-fe
    GEN bin-wrappers/test-wildmatch
    GEN git-remote-testgit
    GEN git-remote-testpy
    CC credential-store.o
    CC abspath.o
    CC advice.o
    CC alias.o
    CC alloc.o
    CC archive.o
    CC archive-tar.o
    CC archive-zip.o
    CC argv-array.o
    CC attr.o
    CC help.o
    CC version.o
    AR xdiff/lib.a
    AR vcs-svn/lib.a
    GEN git-am
    GEN git-bisect
    GEN git-difftool--helper
    GEN git-filter-branch
    GEN git-lost-found
    GEN git-merge-octopus
    GEN git-merge-one-file
    GEN git-merge-resolve
    GEN git-mergetool
    GEN git-pull
    GEN git-quiltimport
    GEN git-rebase
    GEN git-repack
    GEN git-request-pull
    GEN git-stash
    GEN git-submodule
    GEN git-web--browse
    SUBDIR perl
/usr/bin/perl Makefile.PL PREFIX='/var/vcap/packages/git' INSTALL_BASE='' --localedir='/var/vcap/packages/git/share/locale'
    GEN git-p4
    GEN git-instaweb
    AR libgit.a
    LINK git-credential-store
    LINK git-daemon
    LINK git-fast-import
    LINK git-http-backend
    LINK git-imap-send
    LINK git-sh-i18n--envsubst
    LINK git-shell
    LINK git-show-index
    LINK git-upload-pack
    LINK git-remote-testsvn
    LINK git-http-fetch
    LINK git-credential-cache
    LINK git-credential-cache--daemon
    LINK git-remote-http
    GEN git-add--interactive
    GEN git-difftool
    GEN git-archimport
    GEN git-cvsexportcommit
    GEN git-cvsimport
    GEN git-cvsserver
    GEN git-relink
    GEN git-send-email
    GEN git-svn
    LINK git
    LINK test-chmtime
    LINK test-ctype
    LINK test-date
    LINK test-delta
    LINK test-dump-cache-tree
    LINK test-genrandom
    LINK test-index-version
    LINK test-line-buffer
    LINK test-match-trees
    LINK test-mergesort
    LINK test-mktemp
    LINK test-parse-options
    LINK test-path-utils
    LINK test-prio-queue
    LINK test-read-cache
    LINK test-regex
    LINK test-revision-walking
    LINK test-run-command
    LINK test-scrap-cache-tree
    LINK test-sha1
    LINK test-sigchain
    LINK test-string-list
    LINK test-subprocess
    LINK test-svn-fe
    LINK test-wildmatch
    LN/CP git-remote-https
    LN/CP git-remote-ftp
    LN/CP git-remote-ftps
    BUILTIN git-add
    BUILTIN git-annotate
    BUILTIN git-apply
    BUILTIN git-archive
    BUILTIN git-bisect--helper
    BUILTIN git-blame
    BUILTIN git-branch
    BUILTIN git-bundle
    BUILTIN git-cat-file
    BUILTIN git-check-attr
    BUILTIN git-check-ignore
    BUILTIN git-check-mailmap
    BUILTIN git-check-ref-format
    BUILTIN git-checkout-index
    BUILTIN git-checkout
    BUILTIN git-clean
    BUILTIN git-clone
    BUILTIN git-column
    BUILTIN git-commit-tree
    BUILTIN git-commit
    BUILTIN git-config
    BUILTIN git-count-objects
    BUILTIN git-credential
    BUILTIN git-describe
    BUILTIN git-diff-files
    BUILTIN git-diff-index
    BUILTIN git-diff-tree
    BUILTIN git-diff
    BUILTIN git-fast-export
    BUILTIN git-fetch-pack
    BUILTIN git-fetch
    BUILTIN git-fmt-merge-msg
    BUILTIN git-for-each-ref
    BUILTIN git-fsck
    BUILTIN git-gc
    BUILTIN git-grep
    BUILTIN git-hash-object
    BUILTIN git-help
    BUILTIN git-index-pack
    BUILTIN git-init-db
    BUILTIN git-log
    BUILTIN git-ls-files
    BUILTIN git-ls-remote
    BUILTIN git-ls-tree
    BUILTIN git-mailinfo
    BUILTIN git-mailsplit
    BUILTIN git-merge
    BUILTIN git-merge-base
    BUILTIN git-merge-file
    BUILTIN git-merge-index
    BUILTIN git-merge-ours
    BUILTIN git-merge-recursive
    BUILTIN git-merge-tree
    BUILTIN git-mktag
    BUILTIN git-mktree
    BUILTIN git-mv
    BUILTIN git-name-rev
    BUILTIN git-notes
    BUILTIN git-pack-objects
    BUILTIN git-pack-redundant
    BUILTIN git-pack-refs
    BUILTIN git-patch-id
    BUILTIN git-prune-packed
    BUILTIN git-prune
    BUILTIN git-push
    BUILTIN git-read-tree
    BUILTIN git-receive-pack
    BUILTIN git-reflog
    BUILTIN git-remote
    BUILTIN git-remote-ext
    BUILTIN git-remote-fd
    BUILTIN git-replace
    BUILTIN git-rerere
    BUILTIN git-reset
    BUILTIN git-rev-list
    BUILTIN git-rev-parse
    BUILTIN git-revert
    BUILTIN git-rm
    BUILTIN git-send-pack
    BUILTIN git-shortlog
    BUILTIN git-show-branch
    BUILTIN git-show-ref
    BUILTIN git-stripspace
    BUILTIN git-symbolic-ref
    BUILTIN git-tag
    BUILTIN git-tar-tree
    BUILTIN git-unpack-file
    BUILTIN git-unpack-objects
    BUILTIN git-update-index
    BUILTIN git-update-ref
    BUILTIN git-update-server-info
    BUILTIN git-upload-archive
    BUILTIN git-var
    BUILTIN git-verify-pack
    BUILTIN git-verify-tag
    BUILTIN git-write-tree
    BUILTIN git-cherry
    BUILTIN git-cherry-pick
    BUILTIN git-format-patch
    BUILTIN git-fsck-objects
    BUILTIN git-get-tar-commit-id
    BUILTIN git-init
    BUILTIN git-merge-subtree
    BUILTIN git-peek-remote
    BUILTIN git-repo-config
    BUILTIN git-show
    BUILTIN git-stage
    BUILTIN git-status
    BUILTIN git-whatchanged
    SUBDIR git-gui
    MSGFMT    po/de.msg     MSGFMT    po/el.msg     MSGFMT    po/fr.msg 520 translated.
    MSGFMT    po/hu.msg 381 translated, 4 fuzzy, 6 untranslated.
    MSGFMT    po/it.msg 520 translated.
    MSGFMT    po/ja.msg 514 translated.
519 translated, 1 untranslated.
    MSGFMT    po/nb.msg     MSGFMT po/pt_br.msg 520 translated.
    MSGFMT    po/ru.msg 474 translated, 39 untranslated.
    MSGFMT    po/sv.msg 520 translated.
    MSGFMT po/zh_cn.msg 516 translated, 4 untranslated.
    GEN git-gui
521 translated.
366 translated, 7 fuzzy, 17 untranslated.
    INDEX lib/
    SUBDIR gitk-git
Generating catalog po/de.msg
msgfmt --statistics --tcl po/de.po -l de -d po/
Generating catalog po/es.msg
msgfmt --statistics --tcl po/es.po -l es -d po/
Generating catalog po/fr.msg
msgfmt --statistics --tcl po/fr.po -l fr -d po/
Generating catalog po/hu.msg
msgfmt --statistics --tcl po/hu.po -l hu -d po/
Generating catalog po/it.msg
msgfmt --statistics --tcl po/it.po -l it -d po/
Generating catalog po/ja.msg
msgfmt --statistics --tcl po/ja.po -l ja -d po/
Generating catalog po/pt_br.msg
msgfmt --statistics --tcl po/pt_br.po -l pt_br -d po/
Generating catalog po/ru.msg
msgfmt --statistics --tcl po/ru.po -l ru -d po/
Generating catalog po/sv.msg
msgfmt --statistics --tcl po/sv.po -l sv -d po/
    GEN gitk-wish
    SUBDIR perl
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN/Utils.pm >blib/lib/Git/SVN/Utils.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN/GlobSpec.pm >blib/lib/Git/SVN/GlobSpec.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/I18N.pm >blib/lib/Git/I18N.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/IndexInfo.pm >blib/lib/Git/IndexInfo.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN/Ra.pm >blib/lib/Git/SVN/Ra.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git.pm >blib/lib/Git.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN/Log.pm >blib/lib/Git/SVN/Log.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN/Memoize/YAML.pm >blib/lib/Git/SVN/Memoize/YAML.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN/Editor.pm >blib/lib/Git/SVN/Editor.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN/Fetcher.pm >blib/lib/Git/SVN/Fetcher.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN/Prompt.pm >blib/lib/Git/SVN/Prompt.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN/Migration.pm >blib/lib/Git/SVN/Migration.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <Git/SVN.pm >blib/lib/Git/SVN.pm
/usr/bin/perl -pe "s<\Q++LOCALEDIR++\E></var/vcap/packages/git/share/locale>" <private-Error.pm >blib/lib/Error.pm
Manifying blib/man3/Git::SVN::Editor.3pm
Manifying blib/man3/Git::SVN::Memoize::YAML.3pm
Manifying blib/man3/Git::I18N.3pm
Manifying blib/man3/Git.3pm
Manifying blib/man3/Git::SVN::Ra.3pm
Manifying blib/man3/Git::SVN::Fetcher.3pm
Manifying blib/man3/Git::SVN::Prompt.3pm
Manifying blib/man3/private-Error.3pm
Manifying blib/man3/Git::SVN::Utils.3pm
    SUBDIR git_remote_helpers
, Stderr: + tar xzf git/git-1.8.4.tar.gz
+ export HOME=/home/vcap
+ HOME=/home/vcap
+ cp /var/vcap/packages/python/bin/python /usr/bin/python
+ cd git-1.8.4
+ ./configure --prefix=/var/vcap/packages/git
+ make -j 3
GIT_VERSION = 1.8.4
    * new build flags
    * new link flags
    * new prefix flags
wt-status.c: In function 'wt_status_print_unmerged_header':
wt-status.c:182:2: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  status_printf_ln(s, c, "");
  ^
wt-status.c: In function 'wt_status_print_cached_header':
wt-status.c:198:2: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  status_printf_ln(s, c, "");
  ^
wt-status.c: In function 'wt_status_print_dirty_header':
wt-status.c:217:2: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  status_printf_ln(s, c, "");
  ^
wt-status.c: In function 'wt_status_print_other_header':
wt-status.c:229:2: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  status_printf_ln(s, c, "");
  ^
wt-status.c: In function 'wt_status_print_trailer':
wt-status.c:234:2: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  status_printf_ln(s, color(WT_STATUS_HEADER, s), "");
  ^
wt-status.c: In function 'wt_status_print':
wt-status.c:1195:3: warning: zero-length gnu_printf format string [-Wformat-zero-length]
   status_printf(s, color(WT_STATUS_HEADER, s), "");
   ^
wt-status.c:1208:3: warning: zero-length gnu_printf format string [-Wformat-zero-length]
   status_printf_ln(s, color(WT_STATUS_HEADER, s), "");
   ^
wt-status.c:1210:3: warning: zero-length gnu_printf format string [-Wformat-zero-length]
   status_printf_ln(s, color(WT_STATUS_HEADER, s), "");
   ^
wt-status.c:1227:4: warning: zero-length gnu_printf format string [-Wformat-zero-length]
    status_printf_ln(s, GIT_COLOR_NORMAL, "");
    ^
    * new script parameters
    * new Python interpreter location
builtin/commit.c: In function 'prepare_to_commit':
builtin/commit.c:789:4: warning: zero-length gnu_printf format string [-Wformat-zero-length]
    status_printf_ln(s, GIT_COLOR_NORMAL, "");
    ^
0 translated messages, 724 untranslated messages.
14 translated messages.
2133 translated messages, 2 untranslated messages.
po/fr.po:7: warning: header field 'Language' missing in header
716 translated messages, 350 untranslated messages.
0 translated messages, 722 untranslated messages.
799 translated messages, 1281 untranslated messages.
306 translated messages, 687 untranslated messages.
2135 translated messages.
2135 translated messages.
2135 translated messages.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
Writing perl.mak for Git
Writing MYMETA.yml and MYMETA.json
GITGUI_VERSION = 0.18.0
    * new locations or Tcl/Tk interpreter
    * tclsh failed; using unoptimized loading
    * new Tcl/Tk interpreter location
200 translated messages, 7 untranslated messages.
289 translated messages.
276 translated messages, 4 fuzzy translations.
288 translated messages.
283 translated messages, 6 untranslated messages.
284 translated messages.
290 translated messages.
245 translated messages.
304 translated messages.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
make[1]: *** [all] Error 1
make: *** [all] Error 2

**Comment by menicosia** [comment]
Hi @fbonelle,

Yes, we hit the same in our own pipelines. We've updated to stemcell 3094 in story [#106028612](https://www.pivotaltracker.com/story/show/106028612). This will be released in cf-riak-cs-release v11 shortly.

Thanks for the bug report!

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
